# Generated by Django 3.0.5 on 2020-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Print', max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.URLField(default='https://image.flaticon.com/icons/svg/38/38645.svg')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
