# Generated by Django 3.0.5 on 2020-05-04 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=200)),
                ('image', models.URLField(default='https://image.flaticon.com/icons/svg/38/38645.svg')),
                ('image_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
